### ISSUE TITLE
Put glot.io in all Page Titles

### ISSUE THREAD

**Issue by hjc** [prasmussen/glot-www#6]
First off, love the concept and love the site!

But, I have one small request as a KeePass user: Please add the site's title to every page. 

Right now, on pages such as Login, the full title is: `Login`. With KeePass, window titles are used to match applications/sites to entries, and with a title such as `Login`, there's not much I can do to associate the appropriate KeePass entry with `glot.io`.

I imagine this should be pretty quick and would make the site easier to browse in general (since you always have the context, even if it's minimized and you only have a window title).

Thanks!

**Comment by vinnymac** [comment]
@hjc1710 this isn't a difficult change to make, however I don't think it is the correct approach. KeePass requiring a specific title should be a problem they solve not others. I would think you should use an extension for [Firefox](https://addons.mozilla.org/en-US/firefox/addon/add-url-to-window-title/) or [Chrome](https://chrome.google.com/webstore/detail/url-in-title/ignpacbgnbnkaiooknalneoeladjnfgb) to solve that problem instead of having `glot-www` include a url in the title.

**Comment by hjc** [comment]
I'm sorry, that wasn't worded super well. I'm mostly referring to taking the approach the homepage has for the title: `Home - glot.io` and making it consistent across the main logged out pages for the site.That would be: Register, Login, the homepage, and everything under Meta. This gives you the context of the site you're looking at on pages that have fairly common titles. The only thing that would be unaffected, would be actual snippets since their title is descriptive enough there.

For prior art, you can see all of GitHub's logged out pages (literally every page when logged out has `-GitHub`, which I just noticed) or Twitter and YouTube in general. And it doesn't have to be `glot.io`, it can just be the site's title, I just used that because the homepage does.

I just thought it would also be a nice boost to consistent branding and is something I've always appreciated. Take it with a grain of salt!

**Comment by vinnymac** [comment]
Okay, well with those points in mind I will create a pull request for it, and we will see what others think :)
